### ISSUE TITLE
devtools::install() does not take care of package dependencies

### ISSUE THREAD

**Issue by kelshmo** [kelshmo/sageseqr#48]
I removed the explicit calling of library dependencies in #45 and `devtools::install()` should mimic the same environment, since all of the packages are listed in the DESCRIPTION file. 

It does not - I return this error ` could not find function "."`

**Comment by kelshmo** [comment]
I have to explicitly load `plyr`, `edgeR` to run the workflow up to `cqn`.

**Comment by karawoo** [comment]
I think this is the same issue as #42. Adding packages to the Imports field of the DESCRIPTION ensures that they are installed on the user's system, but not necessarily loaded. You still need to either reference the function names with the package they come from (e.g. `plyr::` as you've done elsewhere in the code). This is the offending piece of code is `.(diagnosis)` in this line, which also shows up in the github actions [check results](https://github.com/kelshmo/sageseqr/runs/701095701?check_suite_focus=true#step:5:112):

https://github.com/kelshmo/sageseqr/blob/64b2b433d81909f654b007a5a4cd04d3661be5d0/R/functions.R#L255

I'm not familiar with that syntax, is that a function from plyr?

**Comment by kelshmo** [comment]
Yes. 

I fixed all cases except, when I load`library(sageseqr)`, the problem still remains for `cqn`. 

```
 x fail cqn_counts
Error: target cqn_counts failed.
diagnose(cqn_counts)error$message:
  could not find function "rq"
diagnose(cqn_counts)error$calls:
  1. └─global::cqn(filtered_counts, biomart_results)
  2.   └─cqn::cqn(...)
  3.     └─base::lapply(...)
  4.       └─cqn:::FUN(X[[i]], ...)
```

**Comment by karawoo** [comment]
Ok, I have tested things out with the changes you added to #53 and can reproduce the dependency issues when I try to run `drake::make(plan)`. Yes, I think some of these will need to be fixed in CovariateAnalysis, though you could load the packages in `initialize.R` as a workaround in the meantime. I think that's reasonable in a script that uses the package, just not within the `R/` directory.

For cqn, I looked at their source code and they have made the unfortunate decision to put a bunch of packages in `Depends` and assume that those packages will therefore always be loaded in the user's session, so they haven't bothered to import the functions they are using. These packages are loaded if cqn is loaded, but not when you import specific functionality without loading the whole package. This should ideally be fixed in cqn, but I couldn't find a GitHub repo to do that. So other than loading cqn in initialize.R, which is an option, I think the other workaround would be to reexport the functions that cqn uses from other packages, e.g.

```r
#' @importFrom quantreg rq
#' @export
rq <- quantreg::rq
``` 

quantreg would then need to go in your `Imports`. This is definitely a hack.

For the magrittr error, can you confirm whether you see this with an up-to-date installation of sageseqr? i.e. you've run `devtools::install()` or `devtools::install_github()` recently? If you're loading sageseqr with `library()` and seeing this, it's possible you've got an out of date version installed.
